cfg_name: khushaba1

path:
  data_root: ../data/khushaba1
  save: ../results/khushaba1
  model_path: 

preprocess:
  sampling_freq: 2000
  cutoff_freq: 2
  filter_order: 2
  extraction_rate: 0
  down_sampling_rate: 10
  window_size: 200
  sliding: 50
  fs: 2000

data:
  n_sub : 9
  n_trial : 5
  n_channel : 8
  n_class : 6
  sampling_freq : 2000

validation:
  train_trial : [0,1]
  

seed: 1111


